# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IGU_Principal.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(731, 457)
        MainWindow.setMaximumSize(QtCore.QSize(900, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VLorigenDatos = QtWidgets.QVBoxLayout()
        self.VLorigenDatos.setObjectName("VLorigenDatos")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(705, 211))
        self.groupBox.setMaximumSize(QtCore.QSize(700, 210))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 10, 1692, 195))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.VLgroupBox2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.VLgroupBox2.setContentsMargins(0, 0, 0, 0)
        self.VLgroupBox2.setObjectName("VLgroupBox2")
        self.HLubicacionArch = QtWidgets.QHBoxLayout()
        self.HLubicacionArch.setContentsMargins(-1, -1, 996, -1)
        self.HLubicacionArch.setObjectName("HLubicacionArch")
        self.rbDesdeArch = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbDesdeArch.setMinimumSize(QtCore.QSize(0, 0))
        self.rbDesdeArch.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rbDesdeArch.setChecked(True)
        self.rbDesdeArch.setObjectName("rbDesdeArch")
        self.HLubicacionArch.addWidget(self.rbDesdeArch)
        self.frameUbicacion = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameUbicacion.sizePolicy().hasHeightForWidth())
        self.frameUbicacion.setSizePolicy(sizePolicy)
        self.frameUbicacion.setMinimumSize(QtCore.QSize(230, 50))
        self.frameUbicacion.setMaximumSize(QtCore.QSize(539, 16777215))
        self.frameUbicacion.setFrameShape(QtWidgets.QFrame.Box)
        self.frameUbicacion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUbicacion.setObjectName("frameUbicacion")
        self.txtUbicacion = QtWidgets.QPlainTextEdit(self.frameUbicacion)
        self.txtUbicacion.setGeometry(QtCore.QRect(60, 10, 350, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtUbicacion.sizePolicy().hasHeightForWidth())
        self.txtUbicacion.setSizePolicy(sizePolicy)
        self.txtUbicacion.setMinimumSize(QtCore.QSize(350, 0))
        self.txtUbicacion.setMaximumSize(QtCore.QSize(300, 27))
        self.txtUbicacion.setReadOnly(True)
        self.txtUbicacion.setObjectName("txtUbicacion")
        self.lblUbicArch = QtWidgets.QLabel(self.frameUbicacion)
        self.lblUbicArch.setGeometry(QtCore.QRect(2, 0, 61, 50))
        self.lblUbicArch.setTextFormat(QtCore.Qt.PlainText)
        self.lblUbicArch.setObjectName("lblUbicArch")
        self.btnSelectFile = QtWidgets.QPushButton(self.frameUbicacion)
        self.btnSelectFile.setGeometry(QtCore.QRect(420, 10, 35, 28))
        self.btnSelectFile.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.lblUbicArch.raise_()
        self.btnSelectFile.raise_()
        self.txtUbicacion.raise_()
        self.HLubicacionArch.addWidget(self.frameUbicacion)
        self.VLgroupBox2.addLayout(self.HLubicacionArch)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.VLgroupBox2.addWidget(self.line)
        self.HLgeneracionAleatoria1 = QtWidgets.QHBoxLayout()
        self.HLgeneracionAleatoria1.setContentsMargins(0, -1, 995, -1)
        self.HLgeneracionAleatoria1.setObjectName("HLgeneracionAleatoria1")
        self.VLgeneracionAleatoria1_1 = QtWidgets.QVBoxLayout()
        self.VLgeneracionAleatoria1_1.setContentsMargins(0, 0, -1, 28)
        self.VLgeneracionAleatoria1_1.setSpacing(0)
        self.VLgeneracionAleatoria1_1.setObjectName("VLgeneracionAleatoria1_1")
        self.rbGeneracionAleatoria = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbGeneracionAleatoria.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rbGeneracionAleatoria.setObjectName("rbGeneracionAleatoria")
        self.VLgeneracionAleatoria1_1.addWidget(self.rbGeneracionAleatoria)
        self.VLgeneracionAleatoriaDim = QtWidgets.QVBoxLayout()
        self.VLgeneracionAleatoriaDim.setContentsMargins(27, -1, -1, -1)
        self.VLgeneracionAleatoriaDim.setSpacing(0)
        self.VLgeneracionAleatoriaDim.setObjectName("VLgeneracionAleatoriaDim")
        self.rb2D = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb2D.setEnabled(False)
        self.rb2D.setMinimumSize(QtCore.QSize(0, 0))
        self.rb2D.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rb2D.setChecked(True)
        self.rb2D.setObjectName("rb2D")
        self.VLgeneracionAleatoriaDim.addWidget(self.rb2D)
        self.rb3D = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb3D.setEnabled(False)
        self.rb3D.setMinimumSize(QtCore.QSize(0, 0))
        self.rb3D.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rb3D.setObjectName("rb3D")
        self.VLgeneracionAleatoriaDim.addWidget(self.rb3D)
        self.VLgeneracionAleatoria1_1.addLayout(self.VLgeneracionAleatoriaDim)
        self.HLgeneracionAleatoria1.addLayout(self.VLgeneracionAleatoria1_1)
        self.frameGeneracionAleatoriaRang = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frameGeneracionAleatoriaRang.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGeneracionAleatoriaRang.sizePolicy().hasHeightForWidth())
        self.frameGeneracionAleatoriaRang.setSizePolicy(sizePolicy)
        self.frameGeneracionAleatoriaRang.setMinimumSize(QtCore.QSize(535, 118))
        self.frameGeneracionAleatoriaRang.setMaximumSize(QtCore.QSize(0, 140))
        self.frameGeneracionAleatoriaRang.setFrameShape(QtWidgets.QFrame.Box)
        self.frameGeneracionAleatoriaRang.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneracionAleatoriaRang.setObjectName("frameGeneracionAleatoriaRang")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frameGeneracionAleatoriaRang)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 515, 128))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.VLgeneracionAleatoriaRang = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.VLgeneracionAleatoriaRang.setContentsMargins(0, 0, 0, 0)
        self.VLgeneracionAleatoriaRang.setObjectName("VLgeneracionAleatoriaRang")
        self.frame_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 27))
        self.frame_3.setMaximumSize(QtCore.QSize(210, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 200, 27))
        self.label_2.setMaximumSize(QtCore.QSize(200, 27))
        self.label_2.setObjectName("label_2")
        self.spinCantPuntos = QtWidgets.QSpinBox(self.frame_3)
        self.spinCantPuntos.setGeometry(QtCore.QRect(120, 0, 60, 27))
        self.spinCantPuntos.setMaximumSize(QtCore.QSize(60, 27))
        self.spinCantPuntos.setMinimum(2)
        self.spinCantPuntos.setMaximum(100000)
        self.spinCantPuntos.setProperty("value", 10)
        self.spinCantPuntos.setObjectName("spinCantPuntos")
        self.VLgeneracionAleatoriaRang.addWidget(self.frame_3)
        self.HLrangos = QtWidgets.QHBoxLayout()
        self.HLrangos.setContentsMargins(-1, -1, -1, 0)
        self.HLrangos.setObjectName("HLrangos")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_3.setObjectName("label_3")
        self.HLrangos.addWidget(self.label_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setMinimumSize(QtCore.QSize(15, 0))
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.spinXmin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spinXmin.setMaximumSize(QtCore.QSize(68, 16777215))
        self.spinXmin.setMinimum(-100000.0)
        self.spinXmin.setMaximum(100000.0)
        self.spinXmin.setObjectName("spinXmin")
        self.horizontalLayout_8.addWidget(self.spinXmin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.spinXmax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spinXmax.setMaximumSize(QtCore.QSize(68, 16777215))
        self.spinXmax.setMinimum(-100000.0)
        self.spinXmax.setMaximum(100000.0)
        self.spinXmax.setProperty("value", 5.0)
        self.spinXmax.setObjectName("spinXmax")
        self.horizontalLayout_7.addWidget(self.spinXmax)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.HLrangos.addLayout(self.verticalLayout_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setMinimumSize(QtCore.QSize(15, 0))
        self.label_5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.spinYmin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spinYmin.setMaximumSize(QtCore.QSize(68, 16777215))
        self.spinYmin.setMinimum(-100000.0)
        self.spinYmin.setObjectName("spinYmin")
        self.horizontalLayout_10.addWidget(self.spinYmin)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_10.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.spinYmax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spinYmax.setMaximumSize(QtCore.QSize(68, 16777215))
        self.spinYmax.setMaximum(100000.0)
        self.spinYmax.setProperty("value", 5.0)
        self.spinYmax.setObjectName("spinYmax")
        self.horizontalLayout_9.addWidget(self.spinYmax)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.HLrangos.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setMinimumSize(QtCore.QSize(15, 0))
        self.label_6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.spinZmin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spinZmin.setMaximumSize(QtCore.QSize(68, 16777215))
        self.spinZmin.setMinimum(-100000.0)
        self.spinZmin.setMaximum(100000.0)
        self.spinZmin.setObjectName("spinZmin")
        self.horizontalLayout_14.addWidget(self.spinZmin)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_12.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.spinZmax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spinZmax.setMaximumSize(QtCore.QSize(68, 16777215))
        self.spinZmax.setMinimum(-100000.0)
        self.spinZmax.setMaximum(100000.0)
        self.spinZmax.setProperty("value", 5.0)
        self.spinZmax.setObjectName("spinZmax")
        self.horizontalLayout_13.addWidget(self.spinZmax)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.HLrangos.addLayout(self.verticalLayout_7)
        self.VLgeneracionAleatoriaRang.addLayout(self.HLrangos)
        self.HLgeneracionAleatoria1.addWidget(self.frameGeneracionAleatoriaRang)
        self.VLgroupBox2.addLayout(self.HLgeneracionAleatoria1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.VLorigenDatos.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.VLorigenDatos)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(247, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.VLcriterioGeneracion = QtWidgets.QVBoxLayout()
        self.VLcriterioGeneracion.setContentsMargins(12, -1, -1, -1)
        self.VLcriterioGeneracion.setObjectName("VLcriterioGeneracion")
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 22))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 22))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.rbCantClusters = QtWidgets.QRadioButton(self.frame)
        self.rbCantClusters.setGeometry(QtCore.QRect(0, 0, 654, 20))
        self.rbCantClusters.setChecked(True)
        self.rbCantClusters.setObjectName("rbCantClusters")
        self.spinCantClusters = QtWidgets.QSpinBox(self.frame)
        self.spinCantClusters.setEnabled(True)
        self.spinCantClusters.setGeometry(QtCore.QRect(250, 0, 35, 22))
        self.spinCantClusters.setMaximumSize(QtCore.QSize(35, 16777215))
        self.spinCantClusters.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinCantClusters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinCantClusters.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinCantClusters.setMinimum(1)
        self.spinCantClusters.setMaximum(100000)
        self.spinCantClusters.setObjectName("spinCantClusters")
        self.VLcriterioGeneracion.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 22))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 22))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.rbElemPorCluster = QtWidgets.QRadioButton(self.frame_2)
        self.rbElemPorCluster.setGeometry(QtCore.QRect(0, 0, 446, 20))
        self.rbElemPorCluster.setObjectName("rbElemPorCluster")
        self.spinCantElemPorCluster = QtWidgets.QSpinBox(self.frame_2)
        self.spinCantElemPorCluster.setEnabled(False)
        self.spinCantElemPorCluster.setGeometry(QtCore.QRect(250, 0, 35, 22))
        self.spinCantElemPorCluster.setMaximumSize(QtCore.QSize(35, 16777215))
        self.spinCantElemPorCluster.setMinimum(1)
        self.spinCantElemPorCluster.setMaximum(100000)
        self.spinCantElemPorCluster.setObjectName("spinCantElemPorCluster")
        self.VLcriterioGeneracion.addWidget(self.frame_2)
        self.verticalLayout_5.addLayout(self.VLcriterioGeneracion)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalGroupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox_4.setObjectName("verticalGroupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VLcalculoDistancia = QtWidgets.QVBoxLayout()
        self.VLcalculoDistancia.setContentsMargins(12, -1, -1, -1)
        self.VLcalculoDistancia.setObjectName("VLcalculoDistancia")
        self.rbEuclidea = QtWidgets.QRadioButton(self.verticalGroupBox_4)
        self.rbEuclidea.setChecked(True)
        self.rbEuclidea.setObjectName("rbEuclidea")
        self.VLcalculoDistancia.addWidget(self.rbEuclidea)
        self.rbManhattan = QtWidgets.QRadioButton(self.verticalGroupBox_4)
        self.rbManhattan.setObjectName("rbManhattan")
        self.VLcalculoDistancia.addWidget(self.rbManhattan)
        self.rbMinkowski = QtWidgets.QRadioButton(self.verticalGroupBox_4)
        self.rbMinkowski.setObjectName("rbMinkowski")
        self.VLcalculoDistancia.addWidget(self.rbMinkowski)
        self.verticalLayout_3.addLayout(self.VLcalculoDistancia)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.verticalGroupBox_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.HLgenerar = QtWidgets.QHBoxLayout()
        self.HLgenerar.setObjectName("HLgenerar")
        self.btnGenerar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerar.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btnGenerar.setObjectName("btnGenerar")
        self.HLgenerar.addWidget(self.btnGenerar)
        self.verticalLayout.addLayout(self.HLgenerar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 26))
        self.menubar.setObjectName("menubar")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuAcerca = QtWidgets.QMenu(self.menubar)
        self.menuAcerca.setObjectName("menuAcerca")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuAcerca.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Origen de datos"))
        self.rbDesdeArch.setText(_translate("MainWindow", "Desde Archivo"))
        self.lblUbicArch.setText(_translate("MainWindow", "Ubicación"))
        self.btnSelectFile.setText(_translate("MainWindow", "..."))
        self.rbGeneracionAleatoria.setText(_translate("MainWindow", "Generación Aleatoria"))
        self.rb2D.setText(_translate("MainWindow", "2D"))
        self.rb3D.setText(_translate("MainWindow", "3D"))
        self.label_2.setText(_translate("MainWindow", "Cantidad Puntos"))
        self.label_3.setText(_translate("MainWindow", "Rangos"))
        self.label_4.setText(_translate("MainWindow", "X"))
        self.label_8.setText(_translate("MainWindow", "Min"))
        self.label_7.setText(_translate("MainWindow", "Max"))
        self.label_5.setText(_translate("MainWindow", "Y"))
        self.label_9.setText(_translate("MainWindow", "Min"))
        self.label_10.setText(_translate("MainWindow", "Max"))
        self.label_6.setText(_translate("MainWindow", "Z"))
        self.label_11.setText(_translate("MainWindow", "Min"))
        self.label_12.setText(_translate("MainWindow", "Max"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Criterio de Generación de Clusters"))
        self.rbCantClusters.setText(_translate("MainWindow", "Cantidad Clusters"))
        self.rbElemPorCluster.setText(_translate("MainWindow", "Cantidad Elementos por Cluster"))
        self.verticalGroupBox_4.setTitle(_translate("MainWindow", "Tipo de Distancia"))
        self.rbEuclidea.setText(_translate("MainWindow", "Euclídea"))
        self.rbManhattan.setText(_translate("MainWindow", "Manhattan"))
        self.rbMinkowski.setText(_translate("MainWindow", "Minkowski"))
        self.btnGenerar.setText(_translate("MainWindow", "Generar"))
        self.menuConfig.setTitle(_translate("MainWindow", "Configuración"))
        self.menuAcerca.setTitle(_translate("MainWindow", "A cerca de"))

